### ISSUE TITLE
Unclear instruction for building/using mongo_client

### ISSUE THREAD

**Issue by rradjabi** [auperatech/VMSS2.0#1]
I am referencing this instruction: https://github.com/auperatech/VMSS2.0/blob/main/docs/smart_edge_box/mongo_docker_creation.md

Step 2 is to compile the sample code with `make` but there is no reference to that code. **Please clarify**

Step 3 is to connect to database:
`./mongo_client "mongodb://172.16.1.7:27017" "test_db" "test_collection"`, can you explain if this is to be run from inside the mongo client, from a host, etc? Is the IP 172.16.1.7:27017 the address/port for a typical mongo docker as launched in step 1?

**Comment by zhenmai** [comment]
Thanks for mentioning. The above issues are clarified and the instruction mongo_docker_creation.md has been updated.
Please check that https://github.com/auperatech/VMSS2.0/blob/main/docs/smart_edge_box/mongo_docker_creation.md
